# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('curlattitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('curlongtitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('currentpressure', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('curlattitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('curlongtitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('currentpressure', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
